# Generated by Django 3.2.11 on 2022-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
