# Generated by Django 3.2.11 on 2022-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20220314_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('reactjs', 'react'), ('nodejs', 'nodejs'), ('java', 'java'), ('android', 'android'), ('others', 'others')], max_length=200),
        ),
    ]
