# Generated by Django 3.2.11 on 2022-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_applicationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='jobid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
